/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/

// TODO

'use strict';

const Alexa = require('alexa-sdk');

const APP_ID = undefined;

const languageStrings = {
    'en': {
        translation: {
            QUOTES: [
                "Only I can change my life. No one can do it for me. Carol Burnett",
                "Life is 10% what happens to you and 90% how you react to it. Charles R. Swindoll",
                "With the new day comes new strength and new thoughts. Eleanor Roosevelt",
                "Good, better, best. Never let it rest. Til your good is better and your better is best. St. Jerome",
                "It does not matter how slowly you go as long as you do not stop. Confucius",
                "Always do your best. What you plant now, you will harvest later. Og Mandino",
                "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. Helen Keller",
                "In order to succeed, we must first believe that we can. Nikos Kazantzakis",
                "It always seems impossible until its done. Nelson Mandela",
                "If you can dream it, you can do it. Walt Disney",
                "Failure will never overtake me if my determination to succeed is strong enough. Og Mandino",
                "The secret of getting ahead is getting started. Mark Twain",
                "Infuse your life with action. Dont wait for it to happen. Make it happen. Make your own future. Make your own hope. Make your own love. And whatever your beliefs, honor your creator, not by passively waiting for grace to come down from upon high, but by doing what you can to make grace happen... yourself, right now, right down here on Earth. Bradley Whitford",
                "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. Norman Vincent Peale",
                "The past cannot be changed. The future is yet in your power. Unknown",
                "What you do today can improve all your tomorrows. Ralph Marston",
                "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. Thomas A. Edison",
                "Keep your eyes on the stars, and your feet on the ground. Theodore Roosevelt",
                "To begin, begin. William Wordsworth",
                "Problems are not stop signs, they are guidelines. Robert H. Schuller",
                "We should not give up and we should not allow the problem to defeat us. A. P. J. Abdul Kalam",
                "Accept the challenges so that you can feel the exhilaration of victory. George S. Patton",
                "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step. Lao Tzu",
                "You can't cross the sea merely by standing and staring at the water. Rabindranath Tagore",
                "If you want to conquer fear, don't sit home and think about it. Go out and get busy. Dale Carnegie",
                "Don't watch the clock; do what it does. Keep going. Sam Levenson",
                "Setting goals is the first step in turning the invisible into the visible. Tony Robbins",
                "A creative man is motivated by the desire to achieve, not by the desire to beat others. Ayn Rand",
                "Start where you are. Use what you have. Do what you can. Arthur Ashe",
                "Your talent is God's gift to you. What you do with it is your gift back to God. Leo Buscaglia",
                "If you fell down yesterday, stand up today. H. G. Wells",
                "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence. Confucius",
                "When something is important enough, you do it even if the odds are not in your favor. Elon Musk",
                "Quality is not an act, it is a habit. Aristotle",
                "There is only one corner of the universe you can be certain of improving, and that's your own self. Aldous Huxley",
                "Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again. Og Mandino",
                "Set your goals high, and don't stop till you get there. Bo Jackson",
                "Never, never, never give up. Winston Churchill",
                "You will never win if you never begin. Helen Rowland",
                "You are never too old to set another goal or to dream a new dream. Les Brown",
                "Well done is better than well said. Benjamin Franklin",
                "We may encounter many defeats but we must not be defeated. Maya Angelou",
                "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better. Samuel Beckett",
                "Be kind whenever possible. It is always possible. Dalai Lama",
                "Without hard work, nothing grows but weeds. Gordon B. Hinckley",
                "If you're going through hell, keep going. Winston Churchill",
                "What you get by achieving your goals is not as important as what you become by achieving your goals. Zig Ziglar",
                "Aim for the moon. If you miss, you may hit a star. W. Clement Stone",
                "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious. Stephen Hawking",
                "Perseverance is not a long race; it is many short races one after the other. Walter Elliot",
                "Consult not your fears but your hopes and your dreams. Think not about your frustrations, but about your unfulfilled potential. Concern yourself not with what you tried and failed in, but with what it is still possible for you to do. Pope John XXIII",
                "The way to get started is to quit talking and begin doing. Walt Disney",
                "Knowing is not enough; we must apply. Willing is not enough; we must do. Johann Wolfgang von Goethe",
                "When you reach the end of your rope, tie a knot in it and hang on. Franklin D. Roosevelt",
                "The key is to keep company only with people who uplift you, whose presence calls forth your best. Epictetus",
                "There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living. Nelson Mandela",
                "By failing to prepare, you are preparing to fail. Benjamin Franklin",
                "Either you run the day or the day runs you. Jim Rohn",
                "The harder the conflict, the more glorious the triumph. Thomas Paine",
                "Do you want to know who you are? Don't ask. Act! Action will delineate and define you. Thomas Jefferson",
                "I'd rather attempt to do something great and fail than to attempt to do nothing and succeed. Robert H. Schuller",
                "Opportunity does not knock, it presents itself when you beat down the door. Kyle Chandler",
                "Never give up, for that is just the place and time that the tide will turn. Harriet Beecher Stowe",
                "You are not here merely to make a living. You are here in order to enable the world to live more amply, with greater vision, with a finer spirit of hope and achievement. You are here to enrich the world, and you impoverish yourself if you forget the errand. Woodrow Wilson",
                "Be Impeccable With Your Word. Speak with integrity. Say only what you mean. Avoid using the word to speak against yourself or to gossip about others. Use the power of your word in the direction of truth and love. Don Miguel Ruiz",
                "A good plan violently executed now is better than a perfect plan executed next week. George S. Patton",
                "I know where I'm going and I know the truth, and I don't have to be what you want me to be. I'm free to be what I want. Muhammad Ali",
                "If you don't like how things are, change it! You're not a tree. Jim Rohn",
                "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice. Wayne Dyer",
                "Things do not happen. Things are made to happen. John F. Kennedy",
                "Act as if what you do makes a difference. It does. William James",
                "A goal is a dream with a deadline. Napoleon Hill",
                "Motivation is the art of getting people to do what you want them to do because they want to do it. Dwight D. Eisenhower",
                "If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success. John D. Rockefeller",
                "The people who influence you are the people who believe in you. Henry Drummond",
                "Perseverance is failing 19 times and succeeding the 20th. Julie Andrews",
                "Do your work with your whole heart, and you will succeed - there's so little competition. Elbert Hubbard",
                "Expect problems and eat them for breakfast. Alfred A. Montapert",
                "If you think you can do it, you can. John Burroughs",
                "Never give in and never give up. Hubert H. Humphrey",
                "Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins. Jim Rohn",
                "Poverty was the greatest motivating factor in my life. Jimmy Dean",
                "Change your life today. Don't gamble on the future, act now, without delay. Simone de Beauvoir",
                "You can never quit. Winners never quit, and quitters never win. Ted Turner",
                "It is very important to know who you are. To make decisions. To show who you are. Malala Yousafzai",
                "There's a way to do it better - find it. Thomas A. Edison",
                "The most effective way to do it, is to do it. Amelia Earhart",
                "Do not wait to strike till the iron is hot; but make it hot by striking. William Butler Yeats",
                "Do the one thing you think you cannot do. Fail at it. Try again. Do better the second time. The only people who never tumble are those who never mount the high wire. This is your moment. Own it. Oprah Winfrey",
                "The more man meditates upon good thoughts, the better will be his world and the world at large. Confucius",
                "The ultimate aim of the ego is not to see something, but to be something. Muhammad Iqbal",
                "One way to keep momentum going is to have constantly greater goals. Michael Korda",
                "Even if you fall on your face, you're still moving forward. Victor Kiam",
                "I attribute my success to this - I never gave or took any excuse. Florence Nightingale",
                "Every exit is an entry somewhere else. Tom Stoppard",
                "Follow your dreams, work hard, practice and persevere. Make sure you eat a variety of foods, get plenty of exercise and maintain a healthy lifestyle. Sasha Cohen",
                "After a storm comes a calm. Matthew Henry",
                "Either I will find a way, or I will make one. Philip Sidney",
                "Follow your inner moonlight; don't hide the madness. Allen Ginsberg",
                "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much. Jim Rohn",
                "You simply have to put one foot in front of the other and keep going. Put blinders on and plow right ahead. George Lucas",
                "I am not afraid... I was born to do this. Joan of Arc",
                "You create your opportunities by asking for them. Shakti Gawain",
                "You just can't beat the person who never gives up. Babe Ruth",
                "I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be. Ken Venturi",
                "You can't build a reputation on what you are going to do. Henry Ford",
                "Arriving at one goal is the starting point to another. John Dewey",
                "I learned that we can do anything, but we can't do everything... at least not at the same time. So think of your priorities not in terms of what activities you do, but when you do them. Timing is everything. Dan Millman",
                "Never complain and never explain. Benjamin Disraeli",
                "I've worked too hard and too long to let anything stand in the way of my goals. I will not let my teammates down and I will not let myself down. Mia Hamm",
                "A somebody was once a nobody who wanted to and did. John Burroughs",
                "The will to succeed is important, but what's more important is the will to prepare. Bobby Knight",
                "No bird soars too high if he soars with his own wings. William Blake",
                "I've found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often. Brian Tracy",
                "Go for it now. The future is promised to no one. Wayne Dyer",
                "Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open. Pauline Kael",
                "We are taught you must blame your father, your sisters, your brothers, the school, the teachers - but never blame yourself. It's never your fault. But it's always your fault, because if you wanted to change you're the one who has got to change. Katharine Hepburn",
                "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along. George Herbert",
                "You have to make it happen. Denis Diderot",
                "It's always too early to quit. Norman Vincent Peale",
                "Do something wonderful, people may imitate it. Albert Schweitzer",
                "Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you. George Whitefield",
                "There is always room at the top. Daniel Webster",
                "The first question which the priest and the Levite asked was: 'if I stop to help this man, what will happen to me?', But... the good Samaritan reversed the question: 'if I do not stop to help this man, what will happen to him?', Martin Luther King, Jr.",
                "Whatever you want in life, other people are going to want it too. Believe in yourself enough to accept the idea that you have an equal right to it. Diane Sawyer",
                "Always desire to learn something useful. Sophocles",
                "Pursue one great decisive aim with force and determination. Carl von Clausewitz",
                "Go big or go home. Because it's true. What do you have to lose? Eliza Dushku",
                "I think people who are creative are the luckiest people on earth. I know that there are no shortcuts, but you must keep your faith in something Greater than You, and keep doing what you love. Do what you love, and you will find the way to get it out to the world. Judy Collins",
                "Small deeds done are better than great deeds planned. Peter Marshall",
                "Leap, and the net will appear. John Burroughs",
                "Motivation will almost always beat mere talent. Norman Ralph Augustine",
                "Decide what you want, decide what you are willing to exchange for it. Establish your priorities and go to work. H. L. Hunt",
                "You can't wait for inspiration. You have to go after it with a club. Jack London",
                "To be a good loser is to learn how to win. Carl Sandburg",
                "You have to learn the rules of the game. And then you have to play better than anyone else. Unknown",
                "Never retreat. Never explain. Get it done and let them howl. Benjamin Jowett",
                "The hardships that I encountered in the past will help me succeed in the future. Philip Emeagwali",
                "If you ask me what I came into this life to do, I will tell you: I came to live out loud. Emile Zola",
                "Set your sights high, the higher the better. Expect the most wonderful things to happen, not in the future but right now. Realize that nothing is too good. Allow absolutely nothing to hamper you or hold you up in any way. Eileen Caddy",
                "The more things you do, the more you can do. Lucille Ball",
                "Always continue the climb. It is possible for you to do whatever you choose, if you first get to know who you are and are willing to work with a power that is greater than ourselves to do it. Ella Wheeler Wilcox",
                "A will finds a way. Orison Swett Marden",
                "Be thine own palace, or the world't thy jail. John Donne",
                "You need to overcome the tug of people against you as you reach for high goals. George S. Patton",
                "Deserve your dream. Octavio Paz",
                "Do not weep; do not wax indignant. Understand. Baruch Spinoza",
                "One finds limits by pushing them. Herbert Simon",
                "You must take action now that will move you towards your goals. Develop a sense of urgency in your life. H. Jackson Brown, Jr.",
                "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. Mark Caine",
                "Don't fight the problem, decide it. George C. Marshall",
                "From my tribe I take nothing, I am the maker of my own fortune. Tecumseh",
                "Learn from the past, set vivid, detailed goals for the future, and live in the only moment of time over which you have any control: now. Denis Waitley",
                "In motivating people, you've got to engage their minds and their hearts. I motivate people, I hope, by example - and perhaps by excitement, by having productive ideas to make others feel involved. Rupert Murdoch",
                "Our subliminal mental processes operate outside awareness because they arise in these portions of our mind that are inaccessible to our conscious self; their inaccessibility is due to the architecture of the brain rather than because they have been subject to Freudian motivational forces like repression. Leonard Mlodinow",
                "To know oneself, one should assert oneself. Albert Camus",
                "Don't think, just do. Horace",
                "They can conquer who believe they can. Virgil",
                "The wise does at once what the fool does at last. Baltasar Gracian",
                "Who seeks shall find. Sophocles",
                "God always strives together with those who strive. Aeschylus",
                "Know or listen to those who know. Baltasar Gracian",
                "Be gentle to all and stern with yourself. Saint Teresa of Avila",
                "Wherever you are - be all there. Jim Elliot",
                "Crave for a thing, you will get it. Renounce the craving, the object will follow you by itself. Swami Sivananda",
                "You can't expect to hit the jackpot if you don't put a few nickels in the machine. Flip Wilson",
                "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. It is wonderful how much may be done if we are always doing. Thomas Jefferson",
                "We make the world we live in and shape our own environment. Orison Swett Marden",
                "Only the educated are free. Epictetus",
                "If you don't ask, you don't get. Stevie Wonder",
                "Big shots are only little shots who keep shooting. Christopher Morley",
                "When you fail you learn from the mistakes you made and it motivates you to work even harder. Natalie Gulbis",
                "There is nothing deep down inside us except what we have put there ourselves. Richard Rorty",
                "True happiness involves the full use of one's power and talents. John W. Gardner",
                "He conquers who endures. Persius",
                "I can, therefore I am. Simone Weil",
                "I've always tried to go a step past wherever people expected me to end up. Beverly Sills",
                "We aim above the mark to hit the mark. Ralph Waldo Emerson",
                "Don't give up. Don't lose hope. Don't sell out. Christopher Reeve",
                "Hitch your wagon to a star. Ralph Waldo Emerson",
                "Step by step and the thing is done. Charles Atlas",
                "I am not a has-been. I am a will be. Lauren Bacall",
                "When one must, one can. Charlotte Whitton",
                "March on. Do not tarry. To go forward is to move toward perfection. March on, and fear not the thorns, or the sharp stones on life's path. Khalil Gibran",
                "Your heaviest artillery will be your will to live. Keep that big gun going. Norman Cousins",
                "Get action. Seize the moment. Man was never intended to become an oyster. Theodore Roosevelt",
                "Begin to be now what you will be hereafter. William James",
                "The more we do, the more we can do. William Hazlitt",
                "There is progress whether ye are going forward or backward! The thing is to move! Edgar Cayce",
                "I was motivated to be different in part because I was different. Donna Brazile",
                "I know not age, nor weariness nor defeat. Rose Kennedy",
                "No matter how many goals you have achieved, you must set your sights on a higher one. Jessica Savitch",
                "How do you know you're going to do something, untill you do it? J. D. Salinger",
                "Many are called but few get up. Oliver Herford",
                "The weeds keep multiplying in our garden, which is our mind ruled by fear. Rip them out and call them by name. Sylvia Browne",
                "I come to win. Leo Durocher",
                "Fear of failure, it's the greatest motivational tool. It drives me and drives me and drives me. Jerry West",
                "I really believe that everyone has a talent, ability, or skill that he can mine to support himself and to succeed in life. Dean Koontz",
                "Either move or be moved. Ezra Pound",
                "What is called genius is the abundance of life and health. Henry David Thoreau",
                "To be wholly devoted to some intellectual exercise is to have succeeded in life. Robert Louis Stevenson",
                "One may miss the mark by aiming too high as too low. Thomas Fuller",
            ],
            SKILL_NAME: 'Good Influence',
            GET_QUOTE_MESSAGE: "Here you go: ",
            HELP_MESSAGE: 'You can ask for some motivation, or, you can say exit... How can I help?',
            HELP_REPROMPT: 'How can I help you?',
            STOP_MESSAGE: 'Namaste!',
        },
    },
    'en-US': {
        translation: {
            QUOTES: [
                "Only I can change my life. No one can do it for me. Carol Burnett",
                "Life is 10% what happens to you and 90% how you react to it. Charles R. Swindoll",
                "With the new day comes new strength and new thoughts. Eleanor Roosevelt",
                "Good, better, best. Never let it rest. Til your good is better and your better is best. St. Jerome",
                "It does not matter how slowly you go as long as you do not stop. Confucius",
                "Always do your best. What you plant now, you will harvest later. Og Mandino",
                "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. Helen Keller",
                "In order to succeed, we must first believe that we can. Nikos Kazantzakis",
                "It always seems impossible until its done. Nelson Mandela",
                "If you can dream it, you can do it. Walt Disney",
                "Failure will never overtake me if my determination to succeed is strong enough. Og Mandino",
                "The secret of getting ahead is getting started. Mark Twain",
                "Infuse your life with action. Dont wait for it to happen. Make it happen. Make your own future. Make your own hope. Make your own love. And whatever your beliefs, honor your creator, not by passively waiting for grace to come down from upon high, but by doing what you can to make grace happen... yourself, right now, right down here on Earth. Bradley Whitford",
                "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. Norman Vincent Peale",
                "The past cannot be changed. The future is yet in your power. Unknown",
                "What you do today can improve all your tomorrows. Ralph Marston",
                "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. Thomas A. Edison",
                "Keep your eyes on the stars, and your feet on the ground. Theodore Roosevelt",
                "To begin, begin. William Wordsworth",
                "Problems are not stop signs, they are guidelines. Robert H. Schuller",
                "We should not give up and we should not allow the problem to defeat us. A. P. J. Abdul Kalam",
                "Accept the challenges so that you can feel the exhilaration of victory. George S. Patton",
                "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step. Lao Tzu",
                "You can't cross the sea merely by standing and staring at the water. Rabindranath Tagore",
                "If you want to conquer fear, don't sit home and think about it. Go out and get busy. Dale Carnegie",
                "Don't watch the clock; do what it does. Keep going. Sam Levenson",
                "Setting goals is the first step in turning the invisible into the visible. Tony Robbins",
                "A creative man is motivated by the desire to achieve, not by the desire to beat others. Ayn Rand",
                "Start where you are. Use what you have. Do what you can. Arthur Ashe",
                "Your talent is God's gift to you. What you do with it is your gift back to God. Leo Buscaglia",
                "If you fell down yesterday, stand up today. H. G. Wells",
                "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence. Confucius",
                "When something is important enough, you do it even if the odds are not in your favor. Elon Musk",
                "Quality is not an act, it is a habit. Aristotle",
                "There is only one corner of the universe you can be certain of improving, and that's your own self. Aldous Huxley",
                "Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again. Og Mandino",
                "Set your goals high, and don't stop till you get there. Bo Jackson",
                "Never, never, never give up. Winston Churchill",
                "You will never win if you never begin. Helen Rowland",
                "You are never too old to set another goal or to dream a new dream. Les Brown",
                "Well done is better than well said. Benjamin Franklin",
                "We may encounter many defeats but we must not be defeated. Maya Angelou",
                "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better. Samuel Beckett",
                "Be kind whenever possible. It is always possible. Dalai Lama",
                "Without hard work, nothing grows but weeds. Gordon B. Hinckley",
                "If you're going through hell, keep going. Winston Churchill",
                "What you get by achieving your goals is not as important as what you become by achieving your goals. Zig Ziglar",
                "Aim for the moon. If you miss, you may hit a star. W. Clement Stone",
                "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious. Stephen Hawking",
                "Perseverance is not a long race; it is many short races one after the other. Walter Elliot",
                "Consult not your fears but your hopes and your dreams. Think not about your frustrations, but about your unfulfilled potential. Concern yourself not with what you tried and failed in, but with what it is still possible for you to do. Pope John XXIII",
                "The way to get started is to quit talking and begin doing. Walt Disney",
                "Knowing is not enough; we must apply. Willing is not enough; we must do. Johann Wolfgang von Goethe",
                "When you reach the end of your rope, tie a knot in it and hang on. Franklin D. Roosevelt",
                "The key is to keep company only with people who uplift you, whose presence calls forth your best. Epictetus",
                "There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living. Nelson Mandela",
                "By failing to prepare, you are preparing to fail. Benjamin Franklin",
                "Either you run the day or the day runs you. Jim Rohn",
                "The harder the conflict, the more glorious the triumph. Thomas Paine",
                "Do you want to know who you are? Don't ask. Act! Action will delineate and define you. Thomas Jefferson",
                "I'd rather attempt to do something great and fail than to attempt to do nothing and succeed. Robert H. Schuller",
                "Opportunity does not knock, it presents itself when you beat down the door. Kyle Chandler",
                "Never give up, for that is just the place and time that the tide will turn. Harriet Beecher Stowe",
                "You are not here merely to make a living. You are here in order to enable the world to live more amply, with greater vision, with a finer spirit of hope and achievement. You are here to enrich the world, and you impoverish yourself if you forget the errand. Woodrow Wilson",
                "Be Impeccable With Your Word. Speak with integrity. Say only what you mean. Avoid using the word to speak against yourself or to gossip about others. Use the power of your word in the direction of truth and love. Don Miguel Ruiz",
                "A good plan violently executed now is better than a perfect plan executed next week. George S. Patton",
                "I know where I'm going and I know the truth, and I don't have to be what you want me to be. I'm free to be what I want. Muhammad Ali",
                "If you don't like how things are, change it! You're not a tree. Jim Rohn",
                "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice. Wayne Dyer",
                "Things do not happen. Things are made to happen. John F. Kennedy",
                "Act as if what you do makes a difference. It does. William James",
                "A goal is a dream with a deadline. Napoleon Hill",
                "Motivation is the art of getting people to do what you want them to do because they want to do it. Dwight D. Eisenhower",
                "If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success. John D. Rockefeller",
                "The people who influence you are the people who believe in you. Henry Drummond",
                "Perseverance is failing 19 times and succeeding the 20th. Julie Andrews",
                "Do your work with your whole heart, and you will succeed - there's so little competition. Elbert Hubbard",
                "Expect problems and eat them for breakfast. Alfred A. Montapert",
                "If you think you can do it, you can. John Burroughs",
                "Never give in and never give up. Hubert H. Humphrey",
                "Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins. Jim Rohn",
                "Poverty was the greatest motivating factor in my life. Jimmy Dean",
                "Change your life today. Don't gamble on the future, act now, without delay. Simone de Beauvoir",
                "You can never quit. Winners never quit, and quitters never win. Ted Turner",
                "It is very important to know who you are. To make decisions. To show who you are. Malala Yousafzai",
                "There's a way to do it better - find it. Thomas A. Edison",
                "The most effective way to do it, is to do it. Amelia Earhart",
                "Do not wait to strike till the iron is hot; but make it hot by striking. William Butler Yeats",
                "Do the one thing you think you cannot do. Fail at it. Try again. Do better the second time. The only people who never tumble are those who never mount the high wire. This is your moment. Own it. Oprah Winfrey",
                "The more man meditates upon good thoughts, the better will be his world and the world at large. Confucius",
                "The ultimate aim of the ego is not to see something, but to be something. Muhammad Iqbal",
                "One way to keep momentum going is to have constantly greater goals. Michael Korda",
                "Even if you fall on your face, you're still moving forward. Victor Kiam",
                "I attribute my success to this - I never gave or took any excuse. Florence Nightingale",
                "Every exit is an entry somewhere else. Tom Stoppard",
                "Follow your dreams, work hard, practice and persevere. Make sure you eat a variety of foods, get plenty of exercise and maintain a healthy lifestyle. Sasha Cohen",
                "After a storm comes a calm. Matthew Henry",
                "Either I will find a way, or I will make one. Philip Sidney",
                "Follow your inner moonlight; don't hide the madness. Allen Ginsberg",
                "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much. Jim Rohn",
                "You simply have to put one foot in front of the other and keep going. Put blinders on and plow right ahead. George Lucas",
                "I am not afraid... I was born to do this. Joan of Arc",
                "You create your opportunities by asking for them. Shakti Gawain",
                "You just can't beat the person who never gives up. Babe Ruth",
                "I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be. Ken Venturi",
                "You can't build a reputation on what you are going to do. Henry Ford",
                "Arriving at one goal is the starting point to another. John Dewey",
                "I learned that we can do anything, but we can't do everything... at least not at the same time. So think of your priorities not in terms of what activities you do, but when you do them. Timing is everything. Dan Millman",
                "Never complain and never explain. Benjamin Disraeli",
                "I've worked too hard and too long to let anything stand in the way of my goals. I will not let my teammates down and I will not let myself down. Mia Hamm",
                "A somebody was once a nobody who wanted to and did. John Burroughs",
                "The will to succeed is important, but what's more important is the will to prepare. Bobby Knight",
                "No bird soars too high if he soars with his own wings. William Blake",
                "I've found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often. Brian Tracy",
                "Go for it now. The future is promised to no one. Wayne Dyer",
                "Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open. Pauline Kael",
                "We are taught you must blame your father, your sisters, your brothers, the school, the teachers - but never blame yourself. It's never your fault. But it's always your fault, because if you wanted to change you're the one who has got to change. Katharine Hepburn",
                "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along. George Herbert",
                "You have to make it happen. Denis Diderot",
                "It's always too early to quit. Norman Vincent Peale",
                "Do something wonderful, people may imitate it. Albert Schweitzer",
                "Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you. George Whitefield",
                "There is always room at the top. Daniel Webster",
                "The first question which the priest and the Levite asked was: 'if I stop to help this man, what will happen to me?', But... the good Samaritan reversed the question: 'if I do not stop to help this man, what will happen to him?', Martin Luther King, Jr.",
                "Whatever you want in life, other people are going to want it too. Believe in yourself enough to accept the idea that you have an equal right to it. Diane Sawyer",
                "Always desire to learn something useful. Sophocles",
                "Pursue one great decisive aim with force and determination. Carl von Clausewitz",
                "Go big or go home. Because it's true. What do you have to lose? Eliza Dushku",
                "I think people who are creative are the luckiest people on earth. I know that there are no shortcuts, but you must keep your faith in something Greater than You, and keep doing what you love. Do what you love, and you will find the way to get it out to the world. Judy Collins",
                "Small deeds done are better than great deeds planned. Peter Marshall",
                "Leap, and the net will appear. John Burroughs",
                "Motivation will almost always beat mere talent. Norman Ralph Augustine",
                "Decide what you want, decide what you are willing to exchange for it. Establish your priorities and go to work. H. L. Hunt",
                "You can't wait for inspiration. You have to go after it with a club. Jack London",
                "To be a good loser is to learn how to win. Carl Sandburg",
                "You have to learn the rules of the game. And then you have to play better than anyone else. Unknown",
                "Never retreat. Never explain. Get it done and let them howl. Benjamin Jowett",
                "The hardships that I encountered in the past will help me succeed in the future. Philip Emeagwali",
                "If you ask me what I came into this life to do, I will tell you: I came to live out loud. Emile Zola",
                "Set your sights high, the higher the better. Expect the most wonderful things to happen, not in the future but right now. Realize that nothing is too good. Allow absolutely nothing to hamper you or hold you up in any way. Eileen Caddy",
                "The more things you do, the more you can do. Lucille Ball",
                "Always continue the climb. It is possible for you to do whatever you choose, if you first get to know who you are and are willing to work with a power that is greater than ourselves to do it. Ella Wheeler Wilcox",
                "A will finds a way. Orison Swett Marden",
                "Be thine own palace, or the world't thy jail. John Donne",
                "You need to overcome the tug of people against you as you reach for high goals. George S. Patton",
                "Deserve your dream. Octavio Paz",
                "Do not weep; do not wax indignant. Understand. Baruch Spinoza",
                "One finds limits by pushing them. Herbert Simon",
                "You must take action now that will move you towards your goals. Develop a sense of urgency in your life. H. Jackson Brown, Jr.",
                "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. Mark Caine",
                "Don't fight the problem, decide it. George C. Marshall",
                "From my tribe I take nothing, I am the maker of my own fortune. Tecumseh",
                "Learn from the past, set vivid, detailed goals for the future, and live in the only moment of time over which you have any control: now. Denis Waitley",
                "In motivating people, you've got to engage their minds and their hearts. I motivate people, I hope, by example - and perhaps by excitement, by having productive ideas to make others feel involved. Rupert Murdoch",
                "Our subliminal mental processes operate outside awareness because they arise in these portions of our mind that are inaccessible to our conscious self; their inaccessibility is due to the architecture of the brain rather than because they have been subject to Freudian motivational forces like repression. Leonard Mlodinow",
                "To know oneself, one should assert oneself. Albert Camus",
                "Don't think, just do. Horace",
                "They can conquer who believe they can. Virgil",
                "The wise does at once what the fool does at last. Baltasar Gracian",
                "Who seeks shall find. Sophocles",
                "God always strives together with those who strive. Aeschylus",
                "Know or listen to those who know. Baltasar Gracian",
                "Be gentle to all and stern with yourself. Saint Teresa of Avila",
                "Wherever you are - be all there. Jim Elliot",
                "Crave for a thing, you will get it. Renounce the craving, the object will follow you by itself. Swami Sivananda",
                "You can't expect to hit the jackpot if you don't put a few nickels in the machine. Flip Wilson",
                "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. It is wonderful how much may be done if we are always doing. Thomas Jefferson",
                "We make the world we live in and shape our own environment. Orison Swett Marden",
                "Only the educated are free. Epictetus",
                "If you don't ask, you don't get. Stevie Wonder",
                "Big shots are only little shots who keep shooting. Christopher Morley",
                "When you fail you learn from the mistakes you made and it motivates you to work even harder. Natalie Gulbis",
                "There is nothing deep down inside us except what we have put there ourselves. Richard Rorty",
                "True happiness involves the full use of one's power and talents. John W. Gardner",
                "He conquers who endures. Persius",
                "I can, therefore I am. Simone Weil",
                "I've always tried to go a step past wherever people expected me to end up. Beverly Sills",
                "We aim above the mark to hit the mark. Ralph Waldo Emerson",
                "Don't give up. Don't lose hope. Don't sell out. Christopher Reeve",
                "Hitch your wagon to a star. Ralph Waldo Emerson",
                "Step by step and the thing is done. Charles Atlas",
                "I am not a has-been. I am a will be. Lauren Bacall",
                "When one must, one can. Charlotte Whitton",
                "March on. Do not tarry. To go forward is to move toward perfection. March on, and fear not the thorns, or the sharp stones on life's path. Khalil Gibran",
                "Your heaviest artillery will be your will to live. Keep that big gun going. Norman Cousins",
                "Get action. Seize the moment. Man was never intended to become an oyster. Theodore Roosevelt",
                "Begin to be now what you will be hereafter. William James",
                "The more we do, the more we can do. William Hazlitt",
                "There is progress whether ye are going forward or backward! The thing is to move! Edgar Cayce",
                "I was motivated to be different in part because I was different. Donna Brazile",
                "I know not age, nor weariness nor defeat. Rose Kennedy",
                "No matter how many goals you have achieved, you must set your sights on a higher one. Jessica Savitch",
                "How do you know you're going to do something, untill you do it? J. D. Salinger",
                "Many are called but few get up. Oliver Herford",
                "The weeds keep multiplying in our garden, which is our mind ruled by fear. Rip them out and call them by name. Sylvia Browne",
                "I come to win. Leo Durocher",
                "Fear of failure, it's the greatest motivational tool. It drives me and drives me and drives me. Jerry West",
                "I really believe that everyone has a talent, ability, or skill that he can mine to support himself and to succeed in life. Dean Koontz",
                "Either move or be moved. Ezra Pound",
                "What is called genius is the abundance of life and health. Henry David Thoreau",
                "To be wholly devoted to some intellectual exercise is to have succeeded in life. Robert Louis Stevenson",
                "One may miss the mark by aiming too high as too low. Thomas Fuller",
            ],
            SKILL_NAME: 'Good Influence',
        },
    },
};

const handlers = {
    'LaunchRequest': function () {
        this.emit('GetQuote');
    },
    'MotivateMe': function () {
        this.emit('GetQuote');
    },
    'GetQuote': function () {
        // Get a random quote from the motivation list
        // Use this.t() to get corresponding language data
        const mQuoteArr = this.t('QUOTES');
        const mQuoteIndex = Math.floor(Math.random() * mQuoteArr.length);
        const motivationalQuote = mQuoteArr[mQuoteIndex];

        // Create speech output
        const speechOutput = this.t('GET_QUOTE_MESSAGE') + motivationalQuote;
        this.emit(':tellWithCard', speechOutput, this.t('SKILL_NAME'), motivationalQuote);
    },
    'AMAZON.HelpIntent': function () {
        const speechOutput = this.t('HELP_MESSAGE');
        const reprompt = this.t('HELP_MESSAGE');
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', this.t('STOP_MESSAGE'));
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', this.t('STOP_MESSAGE'));
    },
};

exports.handler = function (event, context) {
    const alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    // To enable string internationalization (i18n) features, set a resources object.
    alexa.resources = languageStrings;
    alexa.registerHandlers(handlers);
    alexa.execute();
};
